# Actor.create(name: '', tmdb_id: , image_url: '')
# Movie.create(name: '', tmdb_id: , image_url: '')
# Role.create(actor_id: , movie_id: )
# Path.create(game_id: , traceable_type: '', traceable_id: )

#######################################
#++++++++++++++++ACTOR++++++++++++++++#
#######################################
Actor.create(name: 'Alexandra Daddario', tmdb_id: 109513, image_url: '/z636bIgZDE2HP6R3z9ij87F1sme.jpg', popularity: 51.99)
Actor.create(name: 'Amrita Acharia', tmdb_id: 1048692, image_url: '/tRtky8vDK9nFpf10Maiq85uCLUH.jpg', popularity: 27.63)
Actor.create(name: 'Andy Serkis', tmdb_id: 1333, image_url: '/nQRsxFveJaUIlZ4GYWDe9uJ6u2f.jpg', popularity: 18.22)
Actor.create(name: 'Beyoncé Knowles', tmdb_id: 14386, image_url: '/xYCtL5BpQFALZGYibVPFsebUs6q.jpg', popularity: 18.77)
Actor.create(name: 'Dwayne Johnson', tmdb_id: 18918, image_url: '/akweMz59qsSoPUJYe7QpjAc2rQp.jpg', popularity: 31.25)
Actor.create(name: 'Emilia Clarke', tmdb_id: 1223786, image_url: '/iNuaYKoWb7psag7Tg3eRucj5sn2.jpg', popularity: 60.0)
Actor.create(name: 'Emma Watson', tmdb_id: 10990, image_url: '/s77hUycSJ4x8RJWHDC9WPgotgxE.jpg', popularity: 28.73)
Actor.create(name: 'Gal Gadot', tmdb_id: 90633, image_url: '/h299BeSGjgjlhmLyRVJ0vrefhK.jpg', popularity: 19.1)
Actor.create(name: 'Henry Cavill', tmdb_id: 73968, image_url: '/h8bn6ybR5Hu58UGJGwb66nrOagV.jpg', popularity: 36.92)
Actor.create(name: 'Johnny Depp', tmdb_id: 85, image_url: '/ctaca3ALycPP0vPhRSYK5DTBEPF.jpg', popularity: 20.37)
Actor.create(name: 'Keanu Reeves', tmdb_id: 6384, image_url: '/bOlYWhVuOiU6azC4Bw6zlXZ5QTC.jpg', popularity: 18.68)
Actor.create(name: 'Lena Headey', tmdb_id: 17286, image_url: '/wcpy6J7KLzmVt0METboX3CZ0Jp.jpg', popularity: 35.51)
Actor.create(name: 'Rose Byrne', tmdb_id: 9827, image_url: '/laJdQNmsuR2iblYUggEqr49LvwJ.jpg', popularity: 26.30)
Actor.create(name: 'Scarlett Johansson', tmdb_id: 1245, image_url: '/8EueDe6rPF0jQU4LSpsH2Rmrqac.jpg', popularity: 26.83)
Actor.create(name: 'Tom Cruise', tmdb_id: 500, image_url: '/3oWEuo0e8Nx8JvkqYCDec2iMY6K.jpg', popularity: 17.86)
Actor.create(name: 'Vin Diesel', tmdb_id: 12835, image_url: '/3RdYMTLoL1X16djGF52cFtJovDT.jpg', popularity: 21.50)
Actor.create(name: 'Zoe Saldana', tmdb_id: 8691, image_url: '/ofNrWiA2KDdqiNxFTLp51HcXUlp.jpg', popularity: 18.62)
#######################################
#++++++++++++++++MOVIE++++++++++++++++#
#######################################
Movie.create(name: '300', tmdb_id: 1271, image_url: '/bYR8O1H1ZlME7Dm9ysfTYZnRDpw.jpg')
Movie.create(name: '300: Rise of an Empire', tmdb_id: 53182, image_url: '/gWQf5j3ZqEfOdW2rIZnkuOOva78.jpg')
Movie.create(name: 'Austin Powers in Goldmember', tmdb_id: 818, image_url: '/tFR7dTbX5BsmoUwKHfa2cWoZbwK.jpg')
Movie.create(name: 'Avatar', tmdb_id: 19995, image_url: '/kmcqlZGaSh20zpTbuoF0Cdn07dT.jpg')
Movie.create(name: 'Batman v Superman: Dawn of Justice', tmdb_id: 209112, image_url: '/cGOPbv9wA5gEejkUN892JrveARt.jpg')
Movie.create(name: 'Captain America: Civil War', tmdb_id: 271110, image_url: '/kSBXou5Ac7vEqKd97wotJumyJvU.jpg')
Movie.create(name: 'Edge of Tomorrow', tmdb_id: 137113, image_url: '/tpoVEYvm6qcXueZrQYJNRLXL88s.jpg')
Movie.create(name: 'Epic', tmdb_id: 116711, image_url: '/dUeXOJCpfWmZd9KaPkq2122J1ji.jpg')
Movie.create(name: 'Fantastic Beasts and Where to Find Them', tmdb_id: 259316, image_url: '/dXwbjYyZH1Se0IS3oVcPdvueLKd.jpg')
Movie.create(name: 'Fast & Furious 6', tmdb_id: 82992, image_url: '/b9gTJKLdSbwcQRKzmqMq3dMfRwI.jpg')
Movie.create(name: 'Furious 7', tmdb_id: 168259, image_url: '/dCgm7efXDmiABSdWDHBDBx2jwmn.jpg')
Movie.create(name: 'Guardians of the Galaxy', tmdb_id: 118340, image_url: '/y31QB9kn3XSudA15tV7UWQ9XLuW.jpg')
Movie.create(name: 'Harry Potter and the Deathly Hallows: Part 2', tmdb_id: 12445, image_url: '/fTplI1NCSuEDP4ITLcTps739fcC.jpg')
Movie.create(name: "Harry Potter and the Philosopher's Stone", tmdb_id: 671, image_url: '/dCtFvscYcXQKTNvyyaQr2g2UacJ.jpg')
Movie.create(name: 'Harry Potter and the Prisoner of Azkaban', tmdb_id: 673, image_url: '/jUFjMoLh8T2CWzHUSjKCojI5SHu.jpg')
Movie.create(name: 'Iron Man 2', tmdb_id: 10138, image_url: '/ArqpkNYGfcTIA6umWt6xihfIZZv.jpg')
Movie.create(name: 'John Wick', tmdb_id: 245891, image_url: '/5vHssUeVe25bMrof1HyaPyWgaP.jpg')
Movie.create(name: 'Man of Steel', tmdb_id: 49521, image_url: '/xWlaTLnD8NJMTT9PGOD9z5re1SL.jpg')
Movie.create(name: 'Me Before You', tmdb_id: 296096, image_url: '/oN5lELHH5Xheiy0YdhnY3JB4hx2.jpg')
Movie.create(name: 'Mission: Impossible - Ghost Protocol', tmdb_id: 56292, image_url: '/s58mMsgIVOFfoXPtwPWJ3hDYpXf.jpg')
Movie.create(name: 'Oblivion', tmdb_id: 75612, image_url: '/hmOzkHlkGvi8x24fYpFSnXvjklv.jpg')
Movie.create(name: 'Percy Jackson: Sea of Monsters', tmdb_id: 76285, image_url: '/k1bhUW7XM5X0yD3iewAEvloFBEo.jpg')
Movie.create(name: 'Percy Jackson & the Olympians: The Lightning Thief', tmdb_id: 32654, image_url: '/5NhyXkodMzDRW8uqtPqlxJsoBhf.jpg')
Movie.create(name: "Pirates of the Caribbean: Dead Man's Chest", tmdb_id: 58, image_url: '/waFr5RVKaQ9dzOt3nQuIVB1FiPu.jpg')
Movie.create(name: 'Pirates of the Caribbean: The Curse of the Black Pearl', tmdb_id: 22, image_url: '/tkt9xR1kNX5R9rCebASKck44si2.jpg')
Movie.create(name: 'San Andreas', tmdb_id: 254128, image_url: '/qey0tdcOp9kCDdEZuJ87yE3crSe.jpg')
Movie.create(name: 'Saving Private Ryan', tmdb_id: 857, image_url: '/miDoEMlYDJhOCvxlzI0wZqBs9Yt.jpg')
Movie.create(name: 'Star Wars: Episode II - Attack of the Clones', tmdb_id: 1894, image_url: '/2vcNFtrZXNwIcBgH5e2xXCmVR8t.jpg')
Movie.create(name: 'Terminator Genisys', tmdb_id: 87101, image_url: '/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg')
Movie.create(name: 'The Avengers', tmdb_id: 24428, image_url: '/cezWGskPY5x7GaglTTRN4Fugfb8.jpg')
Movie.create(name: "The Devil's Double", tmdb_id: 62630, image_url: '/df536wZ17wHIW1hqGJNDXhBE3Hl.jpg')
Movie.create(name: 'The Fate of the Furious', tmdb_id: 337339, image_url: '/iNpz2DgTsTMPaDRZq2tnbqjL2vF.jpg')
Movie.create(name: 'The Hobbit: An Unexpected Journey', tmdb_id: 49051, image_url: '/ysX7vDmSh5O19vFjAi56WL7l4nk.jpg')
Movie.create(name: 'The Lord of the Rings: The Fellowship of the Ring', tmdb_id: 8293, image_url: '/bxVxZb5O9OxCO0oRUNdCnpy9NST.jpg')
Movie.create(name: 'The Lord of the Rings: The Return of the King', tmdb_id: 122, image_url: '/uexxR7Kw1qYbZk0RYaF9Rx5ykbj.jpg')
Movie.create(name: 'The Man from U.N.C.L.E.', tmdb_id: 203801, image_url: '/5ttOaThDVmTpV8iragbrhdfxEep.jpg')
Movie.create(name: 'The Matrix', tmdb_id: 603, image_url: '/hEpWvX6Bp79eLxY1kX5ZZJcme5U.jpg')
Movie.create(name: 'The Matrix Reloaded', tmdb_id: 604, image_url: '/ezIurBz2fdUc68d98Fp9dRf5ihv.jpg')
Movie.create(name: 'The Pink Panther', tmdb_id: 12096, image_url: '/eNzbcO8Mps96Zycg6DSFn9b1aO1.jpg')
Movie.create(name: 'Dead Snow 2: Red vs. Dead', tmdb_id: 241842, image_url: '/dLd6A24aHTTBZo8R7OAFzthr6h2.jpg')
Movie.create(name: 'X-Men: Apocalypse', tmdb_id: 246655, image_url: '/zSouWWrySXshPCT4t3UKCQGayyo.jpg')
Movie.create(name: 'X-Men: First Class', tmdb_id: 49538, image_url: '/7SSm7BfzFoVzmd6fCDccj7qRxc8.jpg')
#######################################
#++++++++++++++++ROLES++++++++++++++++#
#######################################

#######################################
#++++++++++++++++PATHS++++++++++++++++#
#######################################
